TIY_GiftExchange/TIY_GiftExchange/Models/Gift.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;

namespace TIY_GiftExchange.Models
{
    public class Gift
    {
        public int Id { get; set; }
        public string Contents { get; set; }
        public string GiftHint { get; set; }
        public string ColorWrappingPaper { get; set; }
        public double? Height { get; set; }
        public double? Width { get; set; }
        public double? Depth { get; set; }
        public double? Weight { get; set; }
        public bool? IsOpened { get; set; }
        
        public Gift() { }
        public Gift(SqlDataReader reader)
        {
            this.Id = (int)reader["Id"];
            this.Contents = reader["Contents"]?.ToString();
            this.GiftHint = reader["GiftHint"]?.ToString();
            this.ColorWrappingPaper = reader["ColorWrappingPaper"]?.ToString();
            this.Height = (double?)reader["Height"];
            this.Width = (double?)reader["Width"];
            this.Depth = (double?)reader["Depth"];
            this.Weight = (double?)reader["Weight"];
            this.IsOpened = (bool?)reader["IsOpened"];
        }
    }
}

TIY_GiftExchange/TIY_GiftExchange/Controllers/GiftController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TIY_GiftExchange.Models;
using TIY_GiftExchange.Services;

namespace TIY_GiftExchange.Controllers
{
    public class GiftController : Controller
    {
        // GET: Gift
        public ActionResult Index()
        {
            var gifts = new GiftServices().GetAllGifts();
            return View(gifts); //return a List of the Gift Pool
        }

        //GET: Create Gift
        public ActionResult Create()
        {
            return View(); 
        }

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            //Create new Gift
            var gift = new Gift();
            UpdateModel(gift);
            //Put into DB
            var newGift= new GiftServices().CreateGift(gift);
            return RedirectToAction("Index");
        }

        //GET: Id to Edit
        public ActionResult Edit(int id)
        {
            //get gift Id
            var gift = GiftServices.GetGift(id);
            return View(gift);
        }

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            var gift = new Gift();
            //Edit gift with respective Id
            UpdateModel(gift);
            var newGift = new GiftServices().EditGift(gift);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            var gift = GiftServices.GetGift(id);
            return View(gift);
        }
        
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            var gift = new Gift();
            gift.Id= id;
            var newGift= new GiftServices().DeleteGift(gift);
            return RedirectToAction("Index");
        }

        public ActionResult Unopened()
        {
            var gift = new GiftServices().UnopenedGifts();
            return View(gift);
        }

        public ActionResult Open(int id)
        {
            var gift = GiftServices.GetGift(id);
            return View(gift);
        }

        [HttpPost]
        public ActionResult Open(int id, FormCollection collection)
        {
            var gift = new Gift();
            gift.Id = id;
            var newGift = new GiftServices().OpenGift(gift);
            return RedirectToAction("Index");
        }
    }
}

TIY_GiftExchange/TIY_GiftExchange/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TIY_GiftExchange.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

TIY_GiftExchange/TIY_GiftExchange/Views/Gift/Create.cshtml
@model TIY_GiftExchange.Models.Gift

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Gift</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Contents, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Contents, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contents, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiftHint, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiftHint, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiftHint, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ColorWrappingPaper, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ColorWrappingPaper, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ColorWrappingPaper, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Height, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Height, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Height, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Width, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Width, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Width, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Depth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Depth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Depth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Weight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Weight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsOpened, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsOpened, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IsOpened, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TIY_GiftExchange/TIY_GiftExchange/Views/Gift/Delete.cshtml
@model TIY_GiftExchange.Models.Gift

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Gift</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Contents)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Contents)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.GiftHint)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.GiftHint)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ColorWrappingPaper)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ColorWrappingPaper)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Height)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Height)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Width)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Width)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Depth)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Depth)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Weight)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Weight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsOpened)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsOpened)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

TIY_GiftExchange/TIY_GiftExchange/Views/Gift/Edit.cshtml
@model TIY_GiftExchange.Models.Gift

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Gift</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Contents, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Contents, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Contents, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GiftHint, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.GiftHint, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.GiftHint, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ColorWrappingPaper, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ColorWrappingPaper, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ColorWrappingPaper, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Height, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Height, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Height, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Width, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Width, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Width, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Depth, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Depth, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Depth, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Weight, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Weight, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Weight, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.IsOpened, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.IsOpened, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.IsOpened, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TIY_GiftExchange/TIY_GiftExchange/Views/Gift/Index.cshtml
@model IEnumerable<TIY_GiftExchange.Models.Gift>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Show Unopened Gifts Only", "Unopened") |
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            <p>What's Inside?</p>
        </th>
        <th>
            <p>Hint</p>
        </th>
        <th>
            <p>Color</p>
        </th>
        <th>
            <p>Demensions</p>
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Weight)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
        @if (!item.IsOpened.GetValueOrDefault())
        {            
                <h5>UNOPENED!! </h5>         
        }
        else{ 
            @Html.DisplayFor(modelItem => item.Contents)
        }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.GiftHint)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ColorWrappingPaper)
        </td>
        <td>
           @item.Height x @item.Width x @item.Depth
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Weight)
        </td>
        <td>
            @if (!item.IsOpened.GetValueOrDefault())
            {
            @Html.ActionLink("Open", "Open", new { id=item.Id}) 
            } |
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id }) 
        </td>
    </tr>
}

</table>

TIY_GiftExchange/TIY_GiftExchange/Views/Gift/Open.cshtml
@model TIY_GiftExchange.Models.Gift

@{
    ViewBag.Title = "Open";
}

<h2>Open</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <div>
            <h4 class="table">
                @Html.DisplayFor(model => model.GiftHint, new { htmlAttributes = new { @class = "form-control" } })
            </h4>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ColorWrappingPaper, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DisplayFor(model => model.ColorWrappingPaper, new { htmlAttributes = new { @class = "form-control" } })
            </div>
        </div>
        <div>
            <div>dimensions</div>
            <div>
                @Model.Height x @Model.Width x @Model.Depth
            </div>
            <div>
                Weight
            </div>
            <div>
                @Model.Weight
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Open?" class="btn btn-default" />
            </div>
            <div>
                @Html.ActionLink("Nevermind", "Index", null, new { @class = "btn btn-default" });
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

TIY_GiftExchange/TIY_GiftExchange/Views/Gift/Unopened.cshtml
@model IEnumerable<TIY_GiftExchange.Models.Gift>

@{
    ViewBag.Title = "Unopened";
}

<h2>Unopened</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            <p>What's Inside?</p>
        </th>
        <th>
            <p>Hint</p>
        </th>
        <th>
            <p>Color</p>
        </th>
        <th>
            <p>Demensions</p>
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Weight)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @if (!item.IsOpened.GetValueOrDefault())
                {
                    <h5>UNOPENED!! </h5>
                }
                else
                {
                    @Html.DisplayFor(modelItem => item.Contents)
                }
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.GiftHint)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ColorWrappingPaper)
            </td>
            <td>
                @item.Height x @item.Width x @item.Depth
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Weight)
            </td>
            <td>
                @Html.ActionLink("Open", "Open", new { id = item.Id }) |
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

TIY_GiftExchange/TIY_GiftExchange/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

TIY_GiftExchange/TIY_GiftExchange/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

TIY_GiftExchange/TIY_GiftExchange/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

TIY_GiftExchange/TIY_GiftExchange/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Pool of Gifts", "Index", "Gift")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>